<?php


namespace App\Providers;


use Illuminate\Support\ServiceProvider;

class StripeServiceProvider extends ServiceProvider
{

    public function boot(){

        \Stripe\Stripe::setApiKey(config('services.stripe.secret'));
    }

    public function register()
    {
       // parent::register(); // TODO: Change the autogenerated stub
    }
}
